name: ğŸ§¼ Sanitize â€“ Generated Docker Images

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      keep-last:
        description: >
          Delete all untagged images except the last N
        required: false
        default: "1"

jobs:
  delete-pr-tagged-image:
    name: ğŸ—‘ï¸ Delete PR${{github.event.pull_request.number}} Image
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‘ï¸ Delete ğŸ’» Sh image PR${{github.event.pull_request.number}}
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: 01-edu
          name: test-sh
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: PR${{github.event.pull_request.number}}
        continue-on-error: true
        
      - name: ğŸ—‘ï¸ Delete ğŸš€ JS image PR${{github.event.pull_request.number}}
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: 01-edu
          name: test-js
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: PR${{github.event.pull_request.number}}
        continue-on-error: true
  
      - name: ğŸ—‘ï¸ Delete ğŸ§© DOM image PR${{github.event.pull_request.number}}
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: 01-edu
          name: test-dom
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: PR${{github.event.pull_request.number}}
        continue-on-error: true
        
  delete-untagged-images:
    name: ğŸ”¥ Clear Untagged Images
    needs: delete-pr-tagged-image
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”¥ Clear all untagged ğŸ’» Sh images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: 01-edu
          name: test-sh
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: ${{ github.event.inputs.keep-last }}
        continue-on-error: true

      - name: ğŸ”¥ Clear all untagged ğŸš€ JS images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: 01-edu
          name: test-js
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: ${{ github.event.inputs.keep-last }}
        continue-on-error: true

      - name: ğŸ”¥ Clear all untagged ğŸ§© DOM images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: 01-edu
          name: test-dom
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: ${{ github.event.inputs.keep-last }}
        continue-on-error: true
