name: ðŸ”— GA-Misc - Check-Links

on:
  pull_request:
    paths-ignore:
      - ".github/**"
    branches: [master]
    types: [labeled, opened, reopened, synchronize]

jobs:
  GA-Misc-Check-Links:
    name: ðŸ”— Run Check Links
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'ðŸ¤¸ skip-check-links') == false

    steps:
      - name: ðŸ§ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ” Get all changed *.md file(s)
        id: changed-md
        run: |
          echo "changed_files=$(git diff --name-only --merge-base origin/master | grep "\.md$" | xargs)" >> "$GITHUB_OUTPUT"

      - name: ðŸ”— Run Check Links
        if: steps.changed-md.outputs.changed_files != ''
        uses: 01-edu/check-links@v0.2
        with:
          filepath: ${{ steps.changed-md.outputs.changed_files }}
